version: "3.9"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: pathrider
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./Backend
    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn core.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=pathrider
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=3306

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data: