# Generated by Django 5.2.4 on 2026-01-22 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_driver_is_active_driver_latitude_driver_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LuxuryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_driver_rating', models.FloatField(default=4.8)),
                ('premium_multiplier', models.FloatField(default=1.8)),
                ('preferred_vehicle', models.CharField(default='Mercedes / BMW', max_length=50)),
                ('chauffeur_dress_code', models.BooleanField(default=True)),
                ('silent_ride', models.BooleanField(default=False)),
                ('ai_priority_score', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OccasionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate'), ('tour', 'Tour'), ('party', 'Party')], max_length=30)),
                ('event_date', models.DateField()),
                ('event_duration_hours', models.PositiveIntegerField()),
                ('vehicle_count', models.PositiveIntegerField(default=1)),
                ('surge_multiplier', models.FloatField(default=1.2)),
                ('ai_demand_score', models.FloatField(default=1.0)),
                ('requires_uniform_driver', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_ride_limit', models.PositiveIntegerField()),
                ('free_km_per_ride', models.PositiveIntegerField(default=10)),
                ('ai_fraud_score', models.FloatField(default=0.0)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location_text', models.CharField(max_length=500)),
                ('drop_location_text', models.CharField(max_length=500)),
                ('pickup_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('drop_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('drop_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distance_km', models.FloatField()),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('luxury', 'Luxury'), ('bus', 'Bus'), ('traveller', 'Traveller')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('booking_type', models.CharField(choices=[('normal', 'Normal'), ('luxury', 'Luxury'), ('subscription', 'Subscription'), ('occasion', 'Occasion')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('ride_otp', models.CharField(editable=False, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='users.driver')),
                ('luxury_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.luxuryprofile')),
                ('occasion_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.occasionservice')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.subscriptionplan')),
            ],
        ),
    ]
