# Generated by Django 5.2.4 on 2025-10-26 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_driver_created_at_alter_driver_bank_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('ride', 'Ride'), ('earning', 'Earning'), ('system', 'System')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.driver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
