# Generated by Django 5.2.7 on 2026-02-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_driver_is_active_driver_latitude_driver_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.FloatField(default=4.0),
        ),
    ]
